/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Legacy palette — kept until every screen is migrated to the
        // HouseBuddy design system below, so unmigrated pages don't break.
        brand: {
          50: '#eef8f6',
          100: '#d7eeea',
          500: '#116466',
          600: '#0d5557',
          900: '#102027',
        },

        // HouseBuddy design system (see /housebuddy/DESIGN.md)
        surface: '#f9f9ff',
        'surface-dim': '#d3daea',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e7eefe',
        'surface-container-high': '#e2e8f8',
        'surface-container-highest': '#dce2f3',
        'surface-variant': '#dce2f3',
        'on-surface': '#151c27',
        'on-surface-variant': '#3c4a42',
        'inverse-surface': '#2a313d',
        'inverse-on-surface': '#ebf1ff',
        outline: '#6c7a72',
        'outline-variant': '#bbcac0',
        'surface-tint': '#006c4d',
        primary: '#006c4d',
        'on-primary': '#ffffff',
        'primary-container': '#12b886',
        'on-primary-container': '#00412d',
        'inverse-primary': '#50dea9',
        secondary: '#855300',
        'on-secondary': '#ffffff',
        'secondary-container': '#fea619',
        'on-secondary-container': '#684000',
        tertiary: '#575e70',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#9ba2b6',
        'on-tertiary-container': '#323949',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#70fbc4',
        'primary-fixed-dim': '#50dea9',
        'on-primary-fixed': '#002115',
        'on-primary-fixed-variant': '#005139',
        'secondary-fixed': '#ffddb8',
        'secondary-fixed-dim': '#ffb95f',
        'on-secondary-fixed': '#2a1700',
        'on-secondary-fixed-variant': '#653e00',
        'tertiary-fixed': '#dce2f7',
        'tertiary-fixed-dim': '#c0c6db',
        'on-tertiary-fixed': '#141b2b',
        'on-tertiary-fixed-variant': '#404758',
        background: '#f9f9ff',
        'on-background': '#151c27',
      },
      fontFamily: {
        sans: ['Be Vietnam Pro', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-xl': ['Be Vietnam Pro', 'sans-serif'],
        'headline-lg': ['Be Vietnam Pro', 'sans-serif'],
        'headline-lg-mobile': ['Be Vietnam Pro', 'sans-serif'],
        'title-md': ['Be Vietnam Pro', 'sans-serif'],
        'body-lg': ['Be Vietnam Pro', 'sans-serif'],
        'body-md': ['Be Vietnam Pro', 'sans-serif'],
        'label-md': ['Be Vietnam Pro', 'sans-serif'],
        'label-sm': ['Be Vietnam Pro', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'title-md': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '16px',
        'margin-mobile': '20px',
        'tap-target-min': '44px',
      },
      boxShadow: {
        soft: '0 24px 80px rgba(33, 52, 55, 0.14)',
        brand: '0 18px 45px rgba(17, 100, 102, 0.24)',
        ambient: '0 4px 20px rgba(17, 24, 39, 0.06)',
        floating: '0 10px 30px rgba(17, 24, 39, 0.10)',
      },
    },
  },
  plugins: [],
}
